name: Asset contribution
description: Submit an asset to include with MCprep
labels: ["enhancement", "asset-submission"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time provide new assets for MCprep! We only include blocks/rigs/effects/entities that are part of Vanilla Minecraft, and try to generally stick to matching Minecraft style (not stylized), however exetra details that extend the animation of a vanilla-style rig, such as arm bends, are ok and even encouraged.

  - type: textarea
    id: asset-name
    attributes:
      label: Name of asset submission
      description: This should match the name displayed in the MCprep UI.
    validations:
      required: true

  - type: checkboxes
    id: quality-checks
    attributes:
      label: Quality checks
      description: Please ensure all of the following are true for your asset.
      options:
        - label: I have used only vanilla textures (or created images that are derived from vanilla textures)
          required: true
        - label: This is a vanilla minecraft asset/mob/effect
          required: true
        - label: I have verified my asset has the correct scale (1 Blender unit = 1 meter), and the scale has been applied (control+a, scale)
          required: true
        - label: If my asset includes a rig, I certified there is a "root" or "main" bone, and the rig object name ends with the name ".arma" or ".rig" to work well with MCprep
          required: true
        - label: I am the sole creator of this rig, other than any textures by Mojang. Any custom textures I created myself.
          required: true

  - type: textarea
    id: usage-details
    attributes:
      label: Describe any usage details
      description: If there is anything special about this rig, you can explain it here. If you have a video explanation, you may include this too.
    validations:
      required: false

  - type: textarea
    id: credit-name
    attributes:
      label: What name should we use to credit you in the README.md file?
    validations:
      required: false

  - type: textarea
    id: credit-url
    attributes:
      label: What credit url should we use to reference you in the README.md file?
    validations:
      required: false

  - type: checkboxes
    id: certify-confirmation
    attributes:
      label: Confirmation
      options:
        - label: By submitting this asset, I affirm the asset is of my own creation. I understand this asset will be included with MCprep with a CC-BY (attribution) license agreement, and that users of MCprep should refer to [MCprep's readme](https://github.com/TheDuckCow/MCprep#credit) for credit or directly name me for credit when this rig is used.
          required: true
