name: Bug Report/MCprep Issue
description: Report a bug/MCprep issue
labels: ["user-troubleshoot"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report for MCprep! We just need some info. Check here for more info: https://github.com/TheDuckCow/MCprep/issues/322. Please note that if you are looking for general help with Blender itself or a related problem like Mineways, you are better off joining the official [MCprep discord](https://discord.gg/mb8hBUC). **Note that support will not be provided if you're found to have an illegal copy of Minecraft!**

  - type: checkboxes
    id: after-restart
    attributes:
      label: Did the issue happen after restarting Blender?
      description: Many times issues can be solved after restarting Blender
      options:
        - label: Yes, the issue indeed continued after restarting Blender
          required: true

  - type: checkboxes
    id: check-known
    attributes:
      label: Check known issues
      description: Be sure to check against all [known issues](https://github.com/TheDuckCow/MCprep/issues?q=is%3Aissue+is%3Aopen+label%3A%22Known+issue%22) to see if your issue is related to one of those - if so, comment there (instead of creating a new issue).
      options:
        - label: I have checked known issues, and my problem is different
          required: true

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen? Uploading screenshots is very helpful too (https://screenshot.help/).
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: What steps are needed to produce the bug?
      placeholder: 1) First step...
    validations:
      required: true

  - type: textarea
    id: mcprep-version
    attributes:
      label: What version of MCprep are you using?
      placeholder: MCprep 3.#.#
    validations:
      required: true

  - type: textarea
    id: blender-version
    attributes:
      label: What version of Blender are you using?
      placeholder: Blender 3.#
    validations:
      required: true
