from enum import Enum

class TranslateKeys(Enum):
	"""
	Each key represents every string in the entire 
	MCprep codebase (well every string visible to the 
	end user). At runtime, an enum value is passed to 
	a translate function that translates strings to the
	target language, which by default is English.
	"""
	WORLD_IMPORTS_HEADER = "world_imports_header"
	WORLD_EXPORTER_HEADER = "world_exporter_header"
	OBJ_WORLD_IMPORT = "obj_world_import"
	MCPREP_TOOLS = "mcprep_tools"
	MCPREP_PREP_MATERIALS = "mcprep_prep_materials"
	OBJ_INCOMPATIBLE_TEXTURESWAP = "obj_incompatible_textureswap"
	MESHSWAP = "meshswap"
	SELECT_EXPORTER = "select_exporter"
	UI_ALREADY_IMPROVED = "ui_already_improved"
	UI_IMPROVE = "ui_improve"
	CYCLES_OPTIMIZER = "cycles_optimizer"
	ADVANCED = "advanced"
	TEXTURE_PACK_FOLDER = "texture_pack_folder"
	COMBINE_MATERIALS = "combine_materials"
	COMBINE_IMAGES = "combine_images"
	MESHSWAP_SOURCE = "meshswap_source"
	MESHSWAP_FILE_BLEND_ERROR = "meshswap_file_blend_error"
	MESHSWAP_FILE_NOT_FOUND_ERROR = "meshswap_file_not_found_error"
	WORLD_TOOLS_HEADER = "world_tools_header"
	WORLD_SETTINGS_LIGHTING = "world_settings_lighting"
	WORLD_TIME_OF_DAY = "world_time_of_day"
	WORLD_ADD_WORLD_1 = "world_add_world_1"
	WORLD_ADD_WORLD_2 = "world_add_world_2"
	SKIN_SWAPPER_HEADER = "skin_swapper_header"
	SKIN_SELECT = "skin_select"
	NO_SKINS_LOADED = "no_skins_loaded"
	PRESS_TO_RELOAD = "press_to_reload"
	RELOAD_SKINS = "reload_skins"
	APPLY = "apply"
	SKIN_FROM_FILE = "skin_from_file"
	SKIN_FROM_USERNAME = "skin_from_username"
	SKIN_PATH = "skin_path"
	RELOAD_MOBS_BELOW = "reload_mobs_below"
	RELOAD_SKINS_ABOVE = "reload_skins_above"
	MCPREP_MATERIALS_HEADER = "mcprep_materials_header"
	LOAD_MATERIAL_1 = "load_material_1"
	LOAD_MATERIAL_2 = "load_material_2"
	NO_MATERIAL_LOADED = "no_material_loaded"
	RESOURCE_PACK = "resource_pack"
	ENTER_OBJECT_MODE_1 = "enter_object_mode_1"
	ENTER_OBJECT_MODE_2 = "enter_object_mode_2"
	IMPORT_PRERIGGED = "import_prerigged"
	NO_MOBS_IN_CATEGORY_1 = "no_mobs_in_category_1"
	NO_MOBS_IN_CATEGORY_2 = "no_mobs_in_category_2"
	NO_MOBS_IN_CATEGORY_3 = "no_mobs_in_category_3"
	NO_MOBS_LOADED = "no_mobs_loaded"
	RELOAD_ASSETS = "reload_assets"
	SPAWN = "spawn"
	MOB_SPAWNER_FOLDER = "mob_spawner_folder"
	OPEN_MOB_FOLDER = "open_mob_folder"
	CHANGE_MOB_ICON = "change_mob_icon"
	RELOAD_MOBS = "reload_mobs"
	MESHSWAP_BLEND = "meshswap_blend"
	RESET_MESHSWAP_PATH = "reset_meshswap_path"
	NO_BLOCKS_LOADED = "no_blocks_loaded"
	PLACE = "place"
	PLACE_BLOCK = "place_block"
	MESHSWAP_FILE = "meshswap_file"
	ITEM_FROM_TEXTURE = "item_from_texture"
	NO_ITEMS_LOADED = "no_items_loaded"
	PLACE_ITEM = "place_item"
	IMPORT_ENTITIES = "import_entities"
	ENTITY_BLEND = "entity_blend"
	ENTITY_FILE_NOT_FOUND_ERROR = "entity_file_not_found"
	RESET_ENTITY_PATH = "reset_entity_path"
	SPAWN_ENTITY = "spawn_entity"
